# Event Types
DRIVE = "DRIVE"
PICKUP = "PICKUP"
DROPOFF = "DROPOFF"
BREAK = "BREAK"
OFF_DUTY = "OFF_DUTY"
FUEL = "FUEL"

# Speed
AVERAGE_SPEED_KMPH = 80

# FMCSA Limits
MAX_DRIVING_HOURS = 11
MAX_ON_DUTY_HOURS = 14
MAX_CYCLE_HOURS = 70

# Break Rules
BREAK_AFTER_HOURS = 8
BREAK_DURATION = 0.5

# Reset Rules
RESET_DURATION = 10

# Stops
PICKUP_DURATION = 1
DROPOFF_DURATION = 1

# Fuel
FUEL_STOP_DISTANCE_KM = 1609  # 1000 miles
FUEL_STOP_DURATION = 0.5